defaults:
  - model: wavegc
  - writer: wandb
  - metrics: accuracy_masked
  - datasets: amazon
  - dataloader: full_graph
  - transforms: empty
  - _self_
optimizer:
  _target_: torch.optim.AdamW
  _partial_: True
  lr: 0.005
  weight_decay: 1e-4

lr_scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  _partial_: True
  T_max: ${trainer.n_epochs}
  eta_min: 1e-6
  
loss_function:
  _target_: src.loss.MaskedCrossEntropyLoss
trainer:
  log_step: 10
  n_epochs: 500
  epoch_len: 1

  device_tensors: [
      "x",
      "eigvs",
      "U",
      "eigvs_mask",
      "labels",
      "edge_index",
      "train_mask",
      "test_mask",
      "batch_idx"
    ] # which tensors should be on device (ex. GPU)
  resume_from: null # null or path to the checkpoint dir with *.pth and config.yaml
  device: auto # device name or "auto"
  override: True # if True, will override the previous run with the same name
  monitor: "max TestMulticlassAccuracy" # "off" or "max/min metric_name", i.e. our goal is to maximize/minimize metric
  save_period: 5 # checkpoint each save_period epochs in addition to the best epoch
  early_stop: ${trainer.n_epochs} # epochs for early stopping
  save_dir: "saved"
  seed: 1
